diplom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """Пользователи"""
    patronymic = models.CharField('Отчество', max_length=50, null=True, blank=True)
    phone = models.CharField('Номер телефона', max_length=11)

    def __str__(self):
        return str(self.username)


class Category(models.Model):
    """Категории работ"""
    name_category = models.CharField(max_length=100, verbose_name='Категория')
    category_view = models.CharField(max_length=100, default="checkbox", verbose_name='Тип категории')

    def __str__(self):
        return str(self.name_category)


class TypeWork(models.Model):
    """Виды работ"""
    name_work = models.CharField(max_length=100, verbose_name='Название работы')
    work_descrip = models.TextField(verbose_name='Описание работы')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    hours = models.IntegerField(verbose_name='Трудозатраты')
    price = models.IntegerField(verbose_name='Стоимость нормо-часа')
    cost = models.IntegerField(blank=True, null=True, verbose_name='Итоговая стоимость')

    def __str__(self):
        return self.name_work

    def save(self, *args, **kwargs):
        self.cost = self.hours * self.price
        super(TypeWork, self).save(*args, **kwargs)

class Order(models.Model):
    """Заказы"""
    id_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='id пользователя')


class OrderWork(models.Model):
    """Работы заказа"""
    id_order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ')
    id_work = models.ForeignKey(TypeWork, on_delete=models.CASCADE, verbose_name='Работа')

mainapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import *


class UserLoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        # проверка введенных данных
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь {username} не найден')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError('Неверный пароль')
        return self.cleaned_data

    class Meta:
        model = User
        fields = {'username', 'password'}


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'phone', 'password1', 'password2')


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = {'name_category', 'category_view'}


class TypeWorkForm(ModelForm):
    class Meta:
        model = TypeWork
        fields = {'name_work', 'work_descrip', 'category', 'hours', 'price'}

templates/add.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">
    <title>Редактирование</title>
</head>
<body>
    <div class="container">
        <div class="add">
            <a class="btn btn-outline-success" style="margin-top: 20px; margin-bottom: 20px" href="{% url 'calculation' %}" role="button">Главная страница</a>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-outline-primary" value="Сохранить">
            </form>
        </div>
    </div>
</body>
</html>

templates/admin_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">
    <title>Категории</title>
</head>
<body>
<section style="margin: 30px">
    <h1>Категории</h1>
    <div class="time-work">
        <table class="table table-hover" id="pricelist">
            <tr>
                <th scope="col">Категория</th>
                <th scope="col">Вид категории</th>
                <th scope="col">Действие</th>
            </tr>
            {% for category in categories %}
                <tr>
                    <td>{{ category.name_category }}</td>
                    <td>{{ category.category_view }}</td>
                    <td>
                        <a class="btn btn-outline-warning" style="margin-bottom: 10px" href="{% url 'update_category' category.id %}">Изменить</a><br>
                        <a class="btn btn-outline-danger" href="{% url 'delete_category' category.id %}">Удалить</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <a class="btn btn-outline-success" href="{% url 'add_category'%}">Создать новую категорию</a>
</section>
</body>
</html>

templates/admin_work.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">
    <title>Рааботы</title>
</head>
<body>
<section style="margin: 30px">
    <h1>Работы</h1>
    <div class="time-work">
        <table class="table table-hover" id="pricelist">
            <tr>
                <th scope="col">Название работы</th>
                <th scope="col">Описание</th>
                <th scope="col">Категория</th>
                <th scope="col">Трудозатраты</th>
                <th scope="col">Стоимость нормо-часа</th>
                <th scope="col">Итоговая стоимость</th>
                <th scope="col">Действие</th>
            </tr>
            {% for work in works %}
                <tr>
                    <td>{{ work.name_work }}</td>
                    <td>{{ work.work_descrip }}</td>
                    <td>{{ work.category }}</td>
                    <td>{{ work.hours }}</td>
                    <td>{{ work.price }}</td>
                    <td>{{ work.cost }}</td>
                    <td>
                        <a class="btn btn-outline-warning" style="margin-bottom: 10px" href="{% url 'update_work' work.id %}">Изменить</a><br>
                        <a class="btn btn-outline-danger" href="{% url 'delete_work' work.id %}">Удалить</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <a class="btn btn-outline-success" href="{% url 'add_work'%}">Создать новую работу</a>
</section>
</body>
</html>

templates/calculation.html
{% load static %}
{% load auth_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/calculation.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/3.3.4/vue.cjs.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.4.0/axios.js"></script>
	<title>Калькулятор</title>
</head>
<body>
    <header id="header" class="header">
		<div class="navigation">
            <div class="info">
                <div class="logo">
                    <a href="#"><img class="logo_img" src="{% static "img/logo1.svg" %}" alt="logo"></a>
                </div>
                <div class="logo_info">
                    <p class="logo_text1">COST_OF_SITE</p>
                    <p class="logo_text2">Онлайн-калькулятор</p>
                </div>
            </div>
            {% if request.user.is_superuser or request.user|has_group:"Администратор" %}
                <ul class="menu">
                    <li><a href="#calcul">Калькулятор</a></li>
                    <li><a href="#cont">Контакты</a></li>
                    <li><a href="{% url 'admin_category' %}">Редактировать категории</a></li>
                    <li><a href="{% url 'admin_work' %}">Редактировать работы</a></li>
                    <li><a href="{% url 'logout' %}">Выйти</a></li>
                </ul>
            {% elif request.user.is_authenticated %}
                <ul class="menu">
                    <li><a href="#calcul">Калькулятор</a></li>
                    <li><a href="#cont">Контакты</a></li>
                    <li><a href="{% url 'logout' %}">Выйти</a></li>
                </ul>
            {% else %}
                <ul class="menu">
                    <li><a href="{% url 'login' %}">Войти</a></li>
                    <li><a href="{% url 'register' %}">Зарегистрироваться</a></li>
                </ul>
            {% endif %}
		</div>
	</header>
	<section id="main" class="main">
		<div class="greetings">
			<h1 class="main_title">ОЦЕНКА СТОИМОСТИ ПРОЕКТА</h1>
			<p class="main_text">Для определения стоимостной оценки прежде всего необходимо определить операции
                (пакет операций), длительность операций и требуемые ресурсы.<br>Процесс оценки и его результат в
                значительной степени зависят от точности описания содержания, качества доступной информации,
                от стадии проекта.
            </p>
		</div>
	</section>
    {% if request.user.is_authenticated %}
        <p><a name="calcul"></a></p>
	<section id="templates" class="templates">
    {% csrf_token %}
    {% verbatim %}
		<div id="app">
			<div class="container">
				<div class="left">
                    <div v-for="(cat, index) in categories">
                        <div class="block">
                            <h2 class="title">{{ cat.name_category }}</h2>
                                <div v-for="work in works">
                                    <div class="clientChoice">
                                         <div v-if="cat.id == work.category">
                                            <div v-if="cat.category_view == 'radio'">
                                                <div class="choice">
                                                    <label class="custom-radio">
                                                        <input type="radio" :name="cat.name_category" :value="work" v-model="selected_works[index]">
                                                        <span>{{ work.name_work }}</span>
                                                        <div class="price">{{ work.cost }}<span> Р</span></div>
                                                    </label>
                                                </div>
                                            </div>
                                            <div v-else>
                                                <div class="choice">
                                                    <label class="custom-checkbox">
                                                        <input type="checkbox" :value="work" v-model="selected_works[index]">
                                                        <span>{{ work.name_work }}</span>
                                                        <div class="price">{{ work.cost }}<span> Р</span></div>
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
				</div>
				<div class="right">
					<p class="title">Примерная стоимость:</p>
                    <p class="cost">{{ sum }}<span>   Р</span></p>
                    <div class="btn">
                        <button class="button" @click="submit"><span>Получить смету</span></button>
                    </div>
				</div>
			</div>
		</div>
	{% endverbatim %}
	</section>
    {% endif %}
    <footer id="footer" class="footer">
        <p><a name="cont"></a></p>
		<div class="basement">
            <div class="info">
                <div class="logo">
                    <a href="#"><img class="logo_img" src="{% static "img/logo1.svg" %}" alt="logo"></a>
                </div>
                <div class="logo_info">
                    <p class="logo_text1">COST_OF_SITE</p>
                    <p class="logo_text2">Онлайн-калькулятор</p>
                </div>
            </div>
            <div class="footer_dis">
                <p class="dis">ⓒ Сайт создан в рамках выпускной квалификационной работы</p>
            </div>
		</div>
	</footer>
<script>
    var id_user = {{ request.user.id }}     <!--текущий пользователь (после регистрации/авторизации)-->
</script>

<script src="/static/js/script.js"></script>
</body>
</html>

templates/estimates.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Смета пользователя</title>
    <style>
        /*ШРИФТЫ*/
        /*MONTSERRAT*/
        @font-face {
            font-family: 'Montserrat-SemiBold';
            font-style: normal;
            font-weight: normal;
            src: local('Montserrat-SemiBold'),
                url('{% static 'fonts/Montserrat/static/Montserrat-SemiBold.woff' %}') format('woff'),
                url('{% static 'fonts/Montserrat/static/Montserrat-SemiBold.ttf' %}') format('ttf');
        }

        @font-face {
            font-family: 'Montserrat-Bold';
            font-style: normal;
            font-weight: bold;
            src: local('Montserrat-Bold'),
                url('{% static 'fonts/Montserrat/static/Montserrat-Bold.woff' %}') format('woff'),
                url('{% static 'fonts/Montserrat/static/Montserrat-Bold.ttf' %}') format('ttf');
        }

        /*LORA*/
        @font-face {
            font-family: 'Lora-Regular';
            font-style: normal;
            font-weight: normal;
            src: local('Lora-Regular'),
                url('{% static 'fonts/Lora/static/Lora-Regular.woff' %}') format('truetype'),
                url('{% static 'fonts/Lora/static/Lora-Regular.ttf' %}') format('truetype');
        }

        h1 {
            font-family: "Montserrat-Bold";
            font-size: 30px;
            text-align: center;
            margin-top: 20px;
        }

        p {
            font-family: "Lora-Regular";
            font-size: 16px;
            text-align: center;
            margin-top: 10px;
        }

        table {
            margin-top: 10px;
            font-family: "Montserrat-SemiBold";
            font-size: 14px;
            border-collapse: collapse;
            text-align: left;
        }

        th {
            background: #234ffd;
            color: white;
            padding: 10px 20px;
        }

        th, td {
            border-style: solid;
            border-width: 0 1px 1px 0;
            border-color: black;
        }

        td {
            padding-left: 5px;
            background: #eef7ff;
        }

        th:first-child, td:first-child {
            text-align: left;
        }

        .itog {
            font-family: "Montserrat-Bold";
            font-size: 16px;
        }
    </style>
</head>
<body>
    <h1>Уважаемый(ая) {{ user.first_name }}!</h1>
    <p>Смета по выбранным Вами данным готова. Можете ознакомиться с результатами ниже.</p>
    <table border="1" id="pricelist">
        <tr>
            <th>Вид работы</th>
            <th>Категория</th>
            <th>Описание</th>
            <th>Трудозатраты, час</th>
            <th>Стоимость нормо-часа, руб</th>
            <th>Стоимость, руб</th>
        </tr>
        {% for work in works %}
            {% for type in types %}
                {% if type.id == work.id_work_id %}
                    <tr>
                        <td>{{ type.name_work }}</td>
                        <td>{% for category in categories %}
                                {% if category.id == type.category_id %}
                                    {{ category.name_category }}
                                {% endif %}
                        {% endfor %}<br></td>
                        <td>{{ type.work_descrip }}</td>
                        <td>{{ type.hours }}</td>
                        <td>{{ type.price }}</td>
                        <td class="quantity">{{ type.cost }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        {% endfor %}
        <tr>
            <td class="itog">Итоговая стоимость</td>
            <td colspan="4"></td>
            <td class="itog"><span id="total">0</span></td>
        </tr>
    </table>
<script>
    var table = document.querySelector('#pricelist');
    var tds = table.querySelectorAll('.quantity');

    var sum = 0;
    for (var i = 0; i < tds.length; i++) {
        sum += Number(tds[i].innerHTML);
        total.innerHTML = sum;
    }
</script>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/logins.css' %}">
    <title>Авторизация</title>
</head>
<body>
    <header id="header" class="header">
        <div class="navigation">
            <div class="info">
                <div class="logo">
                    <a href="#"><img class="logo_img" src="{% static "img/logo1.svg" %}" alt="logo"></a>
                </div>
                <div class="logo_info">
                    <p class="logo_text1">COST_OF_SITE</p>
                    <p class="logo_text2">Онлайн-калькулятор</p>
                </div>
            </div>
            <ul class="menu">
                <li><a href="{% url 'calculation' %}">На главную</a></li>
            </ul>
        </div>
    </header>
    <section class="all">
        <h1>Авторизация</h1>
        <form method="POST">
            {% csrf_token %}    <!-- добавляется токен для защиты -->
            <div class="block">
                <label for="id_username">Имя пользователя:</label><br>
                <input type="text" name="username" maxlength="150" required id="id_username">
            </div>
            <div class="block">
                <label for="id_password">Пароль:</label><br>
                <input type="password" name="password" required id="id_password">
            </div>
            <div class="but">
                <input type="submit" class="button" value="Войти">
            </div>
        </form>
    </section>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/logins.css' %}">
    <title>Регистрация</title>
</head>
<body>
    <header id="header" class="header">
        <div class="navigation">
            <div class="info">
                <div class="logo">
                    <a href="#"><img class="logo_img" src="{% static "img/logo1.svg" %}" alt="logo"></a>
                </div>
                <div class="logo_info">
                    <p class="logo_text1">COST_OF_SITE</p>
                    <p class="logo_text2">Онлайн-калькулятор</p>
                </div>
            </div>
            <ul class="menu">
                <li><a href="{% url 'calculation' %}">На главную</a></li>
            </ul>
        </div>
    </header>
    <section class="all">
        <h1>Регистрация</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="block">
                <label for="id_username">Имя пользователя:</label>
                <input type="text" name="username" maxlength="150" autofocus required id="id_username">
            </div>
            <div class="block">
                <label for="id_first_name">Ваше имя:</label>
                <input type="text" name="first_name" maxlength="30" id="id_first_name">
            </div>
            <div class="block">
                <label for="id_email">Email:</label>
                <input type="email" name="email" maxlength="254" required id="id_email">
            </div>
            <div class="block">
                <label for="id_phone">Номер телефона:</label>
                <input type="text" name="phone" maxlength="11" required id="id_phone">
            </div>
            <div class="block">
                <label for="id_password1">Пароль:</label>
                <input type="password" name="password1" autocomplete="new-password" required id="id_password1">
            </div>
            <div class="block">
                <label for="id_password2">Подтверждение пароля:</label>
                <input type="password" name="password2" autocomplete="new-password" required id="id_password2">
            </div>
            <div class="block but">
                <input type="submit" class="button" value="Зарегистрироваться">
            </div>
        </form>
    </section>
</body>
</html>

templates/thanks.html
{% load static %}
{% load auth_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/thanks.css' %}">
	<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/3.3.4/vue.cjs.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.4.0/axios.js"></script>
	<title>Спасибо</title>
</head>
<body>
	<header id="header" class="header">
		<div class="navigation">
            <div class="info">
                <div class="logo">
                    <a href="#"><img class="logo_img" src="{% static "img/logo1.svg" %}" alt="logo"></a>
                </div>
                <div class="logo_info">
                    <p class="logo_text1">COST_OF_SITE</p>
                    <p class="logo_text2">Онлайн-калькулятор</p>
                </div>
            </div>
            {% if request.user.is_superuser or request.user|has_group:"Администратор" %}
                <ul class="menu">
                    <li><a href="{% url 'calculation' %}">Калькулятор</a></li>
                    <li><a href="#cont">Контакты</a></li>
                    <li><a href="{% url 'admin_category' %}">Редактировать категории</a></li>
                    <li><a href="{% url 'admin_work' %}">Редактировать работы</a></li>
                    <li><a href="{% url 'logout' %}">Выйти</a></li>
                </ul>
            {% elif request.user.is_authenticated %}
                <ul class="menu">
                    <li><a href="{% url 'calculation' %}">Калькулятор</a></li>
                    <li><a href="#cont">Контакты</a></li>
                    <li><a href="{% url 'logout' %}">Выйти</a></li>
                </ul>
            {% else %}
                <ul class="menu">
                    <li><a href="{% url 'login' %}">Войти</a></li>
                    <li><a href="{% url 'register' %}">Зарегистрироваться</a></li>
                </ul>
            {% endif %}
		</div>
	</header>
	<section id="main" class="main">
		<div class="greetings">
			<h1 class="main_title">Спасибо! Ваша заявка уже у нас!</h1>
            <div class="btn">
                <a href="{% url 'estimate' %}" class="button html">Получить смету html</a>
                <a href="{% url 'generate_pdf_estimate' %}" class="button pdf">Получить смету pdf</a>
                <a href="{% url 'download_pdf_estimate' %}" class="button download">Скачать смету pdf</a>
            </div>
		</div>
	</section>
	<footer id="footer" class="footer">
        <p><a name="cont"></a></p>
		<div class="basement">
            <div class="info">
                <div class="logo">
                    <a href="#"><img class="logo_img" src="{% static "img/logo1.svg" %}" alt="logo"></a>
                </div>
                <div class="logo_info">
                    <p class="logo_text1">COST_OF_SITE</p>
                    <p class="logo_text2">Онлайн-калькулятор</p>
                </div>
            </div>
            <div class="footer_dis">
                <p class="dis">ⓒ Сайт создан в рамках выпускной квалификационной работы</p>
            </div>
		</div>
	</footer>
	<script src="js/script.js"></script>
</body>
</html>